# refine/tools/reporter.py
from datetime import datetime
from pathlib import Path
from typing import Any


def generate_markdown_audit(
    raw_path: str,
    processed_path: str,
    initial_rows: int,
    final_rows: int,
    resolutions: dict[str, str],
    audit_trail: list[str],
    expert_advice: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> str:
    """Generates an executive-ready Markdown audit report documenting all data pipeline operations."""
    report_path = Path(processed_path).with_name(f"{Path(processed_path).stem}_audit_report.md")

    strategy_rows = []
    for col, strat in resolutions.items():
        if strat.startswith("MANUAL_INPUT:"):
            val = strat.split(":", 1)[1]
            strat_display = f"MANUAL_INPUT (override: `{val}`)"
        else:
            strat_display = strat
        strategy_rows.append(f"| `{col}` | **{strat_display}** | Human Approved |")
    strategy_table = "\n".join(strategy_rows)

    audit_bullets = "\n".join([f"- {log}" for log in audit_trail])

    meta = metadata or {}
    meta_lines = []
    if meta.get("session_id"):
        meta_lines.append(f"- **Session ID:** `{meta['session_id']}`")
    if meta.get("execution_duration_sec") is not None:
        meta_lines.append(f"- **Execution Duration:** {meta['execution_duration_sec']:.2f}s")
    if meta.get("random_seed") is not None:
        meta_lines.append(f"- **Random Seed:** {meta['random_seed']}")
    meta_str = ("\n".join(meta_lines) + "\n") if meta_lines else ""

    # F-string başlangıcı
    report_content = f"""# Data Pipeline Audit & Governance Report
- **Execution Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
- **Raw Source:** `{raw_path}`
- **Target Destination:** `{processed_path}`
{meta_str}---

## Executive Summary
| Metric | Initial State | Final State | Delta |
| :--- | :--- | :--- | :--- |
| **Total Records** | {initial_rows:,} | {final_rows:,} | {final_rows - initial_rows:+,} |
| **Integrity Status** | Anomalies Detected | Remediated & Validated | Passed |

---

## Human-in-the-Loop (HITL) Resolutions
The human operator intervened and executed the following governance actions:

| Feature | Strategy Selected | Authorization |
| :--- | :--- | :--- |
{strategy_table if strategy_table else "| None | No intervention required | Auto |"}

---

## Senior Data Architect Assessment
```text
{expert_advice or "Standard automated operational governance applied."}
```

---

## Audit Trail
{audit_bullets if audit_bullets else "- No operations recorded."}

---

*Report generated by refine-ai v0.2.0*
"""

    report_path.write_text(report_content)
    return str(report_path)
